# Generated by Django 4.1 on 2022-10-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num_liked',
            field=models.IntegerField(default=0),
        ),
    ]
