<<<<<<< HEAD
# Generated by Django 4.1 on 2022-10-29 19:21
=======
# Generated by Django 4.1 on 2022-10-26 16:55
>>>>>>> infografis

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='UserHealthStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_update', models.DateField(auto_now_add=True)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=6)),
                ('bmr', models.FloatField()),
                ('bmi', models.FloatField()),
                ('calories_intake', models.IntegerField(default=0)),
=======
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField()),
>>>>>>> infografis
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
