# Generated by Django 4.1 on 2022-10-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uhealths', '0004_commentketiga_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentketiga',
            old_name='username',
            new_name='nama',
        ),
    ]
