# Generated by Django 4.1 on 2022-10-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uhealths', '0005_rename_username_commentketiga_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commentkedua',
            name='nama',
            field=models.TextField(blank=True, null=True),
        ),
    ]
